/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Texto = IDL.Record({
  'id' : IDL.Nat,
  'categoria' : IDL.Text,
  'titulo' : IDL.Text,
  'autor' : IDL.Text,
  'conteudo' : IDL.Text,
  'dataCriacao' : IDL.Int,
  'usuarioId' : IDL.Text,
});
export const Anotacao = IDL.Record({
  'id' : IDL.Nat,
  'cor' : IDL.Text,
  'conteudo' : IDL.Text,
  'textoId' : IDL.Nat,
  'dataCriacao' : IDL.Int,
  'usuarioId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ConfiguracaoLeitura = IDL.Record({
  'espacamentoLetras' : IDL.Text,
  'corFundo' : IDL.Text,
  'espacamentoLinhas' : IDL.Text,
  'modoFoco' : IDL.Bool,
  'larguraColuna' : IDL.Nat,
  'usuarioId' : IDL.Text,
  'tamanhoFonte' : IDL.Nat,
});
export const Conquista = IDL.Record({
  'id' : IDL.Nat,
  'marco' : IDL.Text,
  'dataConquista' : IDL.Int,
  'descricao' : IDL.Text,
  'nome' : IDL.Text,
  'usuarioId' : IDL.Text,
});
export const Desafio = IDL.Record({
  'id' : IDL.Nat,
  'recompensaTokens' : IDL.Nat,
  'titulo' : IDL.Text,
  'descricao' : IDL.Text,
  'ativo' : IDL.Bool,
  'tipo' : IDL.Text,
  'metaValor' : IDL.Nat,
});
export const Progresso = IDL.Record({
  'percentualLido' : IDL.Nat,
  'textoId' : IDL.Nat,
  'usuarioId' : IDL.Text,
  'ultimaLeitura' : IDL.Int,
});
export const ProgressoDesafio = IDL.Record({
  'concluido' : IDL.Bool,
  'dataConclusao' : IDL.Int,
  'desafioId' : IDL.Nat,
  'usuarioId' : IDL.Text,
  'progressoAtual' : IDL.Nat,
});
export const EntradaRanking = IDL.Record({
  'nome' : IDL.Text,
  'tokens' : IDL.Nat,
});
export const Recompensa = IDL.Record({
  'id' : IDL.Nat,
  'descricao' : IDL.Text,
  'valor' : IDL.Nat,
  'data' : IDL.Int,
  'usuarioId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buscarTextosPorTitulo' : IDL.Func([IDL.Text], [IDL.Vec(Texto)], ['query']),
  'criarAnotacao' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'criarDesafio' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'criarTexto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deletarAnotacao' : IDL.Func([IDL.Nat], [], []),
  'deletarTexto' : IDL.Func([IDL.Nat], [], []),
  'editarAnotacao' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'editarTexto' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAnotacao' : IDL.Func([IDL.Nat], [IDL.Opt(Anotacao)], ['query']),
  'getAnotacoesTexto' : IDL.Func([IDL.Nat], [IDL.Vec(Anotacao)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfiguracaoLeitura' : IDL.Func(
      [],
      [IDL.Opt(ConfiguracaoLeitura)],
      ['query'],
    ),
  'getConquistas' : IDL.Func([], [IDL.Vec(Conquista)], ['query']),
  'getDesafio' : IDL.Func([IDL.Nat], [IDL.Opt(Desafio)], ['query']),
  'getDesafiosAtivos' : IDL.Func([], [IDL.Vec(Desafio)], ['query']),
  'getDesafiosExemplo' : IDL.Func([], [IDL.Vec(Desafio)], ['query']),
  'getProgresso' : IDL.Func([IDL.Nat], [IDL.Opt(Progresso)], ['query']),
  'getProgressoDesafio' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProgressoDesafio)],
      ['query'],
    ),
  'getRanking' : IDL.Func([], [IDL.Vec(EntradaRanking)], ['query']),
  'getRecompensas' : IDL.Func([], [IDL.Vec(Recompensa)], ['query']),
  'getSaldoAluno' : IDL.Func([], [IDL.Nat], ['query']),
  'getTexto' : IDL.Func([IDL.Nat], [IDL.Opt(Texto)], ['query']),
  'getTextosExemplo' : IDL.Func([], [IDL.Vec(Texto)], ['query']),
  'getTodasAnotacoes' : IDL.Func([], [IDL.Vec(Anotacao)], ['query']),
  'getTodosProgressosDesafio' : IDL.Func(
      [],
      [IDL.Vec(ProgressoDesafio)],
      ['query'],
    ),
  'getTodosTextos' : IDL.Func([], [IDL.Vec(Texto)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listarTextosPorCategoria' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Texto)],
      ['query'],
    ),
  'resgatarSaldo' : IDL.Func([], [IDL.Nat], []),
  'salvarConfiguracaoLeitura' : IDL.Func([ConfiguracaoLeitura], [], []),
  'salvarProgresso' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Texto = IDL.Record({
    'id' : IDL.Nat,
    'categoria' : IDL.Text,
    'titulo' : IDL.Text,
    'autor' : IDL.Text,
    'conteudo' : IDL.Text,
    'dataCriacao' : IDL.Int,
    'usuarioId' : IDL.Text,
  });
  const Anotacao = IDL.Record({
    'id' : IDL.Nat,
    'cor' : IDL.Text,
    'conteudo' : IDL.Text,
    'textoId' : IDL.Nat,
    'dataCriacao' : IDL.Int,
    'usuarioId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ConfiguracaoLeitura = IDL.Record({
    'espacamentoLetras' : IDL.Text,
    'corFundo' : IDL.Text,
    'espacamentoLinhas' : IDL.Text,
    'modoFoco' : IDL.Bool,
    'larguraColuna' : IDL.Nat,
    'usuarioId' : IDL.Text,
    'tamanhoFonte' : IDL.Nat,
  });
  const Conquista = IDL.Record({
    'id' : IDL.Nat,
    'marco' : IDL.Text,
    'dataConquista' : IDL.Int,
    'descricao' : IDL.Text,
    'nome' : IDL.Text,
    'usuarioId' : IDL.Text,
  });
  const Desafio = IDL.Record({
    'id' : IDL.Nat,
    'recompensaTokens' : IDL.Nat,
    'titulo' : IDL.Text,
    'descricao' : IDL.Text,
    'ativo' : IDL.Bool,
    'tipo' : IDL.Text,
    'metaValor' : IDL.Nat,
  });
  const Progresso = IDL.Record({
    'percentualLido' : IDL.Nat,
    'textoId' : IDL.Nat,
    'usuarioId' : IDL.Text,
    'ultimaLeitura' : IDL.Int,
  });
  const ProgressoDesafio = IDL.Record({
    'concluido' : IDL.Bool,
    'dataConclusao' : IDL.Int,
    'desafioId' : IDL.Nat,
    'usuarioId' : IDL.Text,
    'progressoAtual' : IDL.Nat,
  });
  const EntradaRanking = IDL.Record({ 'nome' : IDL.Text, 'tokens' : IDL.Nat });
  const Recompensa = IDL.Record({
    'id' : IDL.Nat,
    'descricao' : IDL.Text,
    'valor' : IDL.Nat,
    'data' : IDL.Int,
    'usuarioId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buscarTextosPorTitulo' : IDL.Func([IDL.Text], [IDL.Vec(Texto)], ['query']),
    'criarAnotacao' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'criarDesafio' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'criarTexto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deletarAnotacao' : IDL.Func([IDL.Nat], [], []),
    'deletarTexto' : IDL.Func([IDL.Nat], [], []),
    'editarAnotacao' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'editarTexto' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAnotacao' : IDL.Func([IDL.Nat], [IDL.Opt(Anotacao)], ['query']),
    'getAnotacoesTexto' : IDL.Func([IDL.Nat], [IDL.Vec(Anotacao)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfiguracaoLeitura' : IDL.Func(
        [],
        [IDL.Opt(ConfiguracaoLeitura)],
        ['query'],
      ),
    'getConquistas' : IDL.Func([], [IDL.Vec(Conquista)], ['query']),
    'getDesafio' : IDL.Func([IDL.Nat], [IDL.Opt(Desafio)], ['query']),
    'getDesafiosAtivos' : IDL.Func([], [IDL.Vec(Desafio)], ['query']),
    'getDesafiosExemplo' : IDL.Func([], [IDL.Vec(Desafio)], ['query']),
    'getProgresso' : IDL.Func([IDL.Nat], [IDL.Opt(Progresso)], ['query']),
    'getProgressoDesafio' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProgressoDesafio)],
        ['query'],
      ),
    'getRanking' : IDL.Func([], [IDL.Vec(EntradaRanking)], ['query']),
    'getRecompensas' : IDL.Func([], [IDL.Vec(Recompensa)], ['query']),
    'getSaldoAluno' : IDL.Func([], [IDL.Nat], ['query']),
    'getTexto' : IDL.Func([IDL.Nat], [IDL.Opt(Texto)], ['query']),
    'getTextosExemplo' : IDL.Func([], [IDL.Vec(Texto)], ['query']),
    'getTodasAnotacoes' : IDL.Func([], [IDL.Vec(Anotacao)], ['query']),
    'getTodosProgressosDesafio' : IDL.Func(
        [],
        [IDL.Vec(ProgressoDesafio)],
        ['query'],
      ),
    'getTodosTextos' : IDL.Func([], [IDL.Vec(Texto)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listarTextosPorCategoria' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Texto)],
        ['query'],
      ),
    'resgatarSaldo' : IDL.Func([], [IDL.Nat], []),
    'salvarConfiguracaoLeitura' : IDL.Func([ConfiguracaoLeitura], [], []),
    'salvarProgresso' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };