/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Anotacao {
  'id' : bigint,
  'cor' : string,
  'conteudo' : string,
  'textoId' : bigint,
  'dataCriacao' : bigint,
  'usuarioId' : string,
}
export interface ConfiguracaoLeitura {
  'espacamentoLetras' : string,
  'corFundo' : string,
  'espacamentoLinhas' : string,
  'modoFoco' : boolean,
  'larguraColuna' : bigint,
  'usuarioId' : string,
  'tamanhoFonte' : bigint,
}
export interface Progresso {
  'percentualLido' : bigint,
  'textoId' : bigint,
  'usuarioId' : string,
  'ultimaLeitura' : bigint,
}
export interface Texto {
  'id' : bigint,
  'categoria' : string,
  'titulo' : string,
  'autor' : string,
  'conteudo' : string,
  'dataCriacao' : bigint,
  'usuarioId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buscarTextosPorTitulo' : ActorMethod<[string], Array<Texto>>,
  'criarAnotacao' : ActorMethod<[bigint, string, string], bigint>,
  'criarTexto' : ActorMethod<[string, string, string, string], bigint>,
  'deletarAnotacao' : ActorMethod<[bigint], undefined>,
  'deletarTexto' : ActorMethod<[bigint], undefined>,
  'editarAnotacao' : ActorMethod<[bigint, string, string], undefined>,
  'editarTexto' : ActorMethod<[bigint, string, string, string], undefined>,
  'getAnotacao' : ActorMethod<[bigint], [] | [Anotacao]>,
  'getAnotacoesTexto' : ActorMethod<[bigint], Array<Anotacao>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfiguracaoLeitura' : ActorMethod<[], [] | [ConfiguracaoLeitura]>,
  'getProgresso' : ActorMethod<[bigint], [] | [Progresso]>,
  'getTexto' : ActorMethod<[bigint], [] | [Texto]>,
  'getTextosExemplo' : ActorMethod<[], Array<Texto>>,
  'getTodasAnotacoes' : ActorMethod<[], Array<Anotacao>>,
  'getTodosTextos' : ActorMethod<[], Array<Texto>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listarTextosPorCategoria' : ActorMethod<[string], Array<Texto>>,
  'salvarConfiguracaoLeitura' : ActorMethod<[ConfiguracaoLeitura], undefined>,
  'salvarProgresso' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];